name: Security-Scan-Visual

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  trivy_visual_scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write # Permissão crucial para escrever na aba Security
      actions: read

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Rodar Trivy (Gera relatório SARIF)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'sarif' # Muda o formato de texto para SARIF
          output: 'trivy-results.sarif' # Nome do arquivo de saída
          severity: 'CRITICAL,HIGH,MEDIUM,LOW,UNKNOWN'

      - name: Upload do resultado para o GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always() # Garante que o upload aconteça mesmo se encontrar falhas
        with:
          sarif_file: 'trivy-results.sarif'